### ISSUE TITLE
Place the ComponentTray bar on any side of the form?

### ISSUE THREAD

**Issue by PeterPanino** [lynatan/ComponentTray#1]
Thank you! You are a genius!
Currently, the ComponentTray bar is always placed on the left side of the form.
How can I place the ComponentTray bar on any side of the form? (Left, Right, Top, Bottom).
Please implement this!
Thank you!

**Comment by ortuagustin** [comment]
Right click on the bar, position -> choose Left, Right, Top or Bottom

**Comment by PeterPanino** [comment]
Many thanks! I was begging Embarcadero for this for many years and now you have it here as a Christmas present. Thank you!
