### ISSUE TITLE
Consider sort/filter the list

### ISSUE THREAD

**Issue by zuobaoquan** [lynatan/ComponentTray#5]
Although there have been such feature for all controls/components, it is still useful to narrow the scope.

**Comment by zuobaoquan** [comment]
P.S. Sort by name or type of component

**Comment by PeterPanino** [comment]
I Agree. Sorting by name or type of component and filtering would be very useful.

**Comment by superswanman** [comment]
Added filtering and sorting to context menu, is that alright like this?
