### ISSUE TITLE
Support data module

### ISSUE THREAD

**Issue by zuobaoquan** [lynatan/ComponentTray#8]
It seems ComponentTray doesn't work in data module? It'll be useful. e.g. actions, data fields? or list all (in case provide a different view different from the datamodule itself)

**Comment by superswanman** [comment]
It is by design. TDataModule is excluded intentionally.
If you want to use in TDataModule, please remove this block.
https://github.com/lynatan/ComponentTray/blob/master/src/UComponentTray.pas#L673

**Comment by zuobaoquan** [comment]
Thanks anyway.
